<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.8.1.0</Version>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <LangVersion>14.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>KRWardrobeCleaner</AssemblyName>
    <RootNamespace>KRWardrobeCleaner</RootNamespace>
    <Author>yaaung-ai</Author>
    <Name>히메짱 옷장 정리기</Name>
    <Punchline>만사가 귀찮은 공주님들을 위한 자동 정리 집사님!</Punchline>
    <Description>만사가 귀찮은 공주님들을 위한 자동 정리 집사님!</Description>
    <RepoUrl>https://github.com/yaaung-ai/KRWardrobeCleaner</RepoUrl>
    <Tags>glamour;inventory;armoire;utility</Tags>
  </PropertyGroup>
</Project>
